-- MySQL Script generated by MySQL Workbench
-- 12/25/16 10:25:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjetoIntegrador
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProjetoIntegrador` ;

-- -----------------------------------------------------
-- Schema ProjetoIntegrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoIntegrador` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `ProjetoIntegrador` ;

-- -----------------------------------------------------
-- Table `ProjetoIntegrador`.`ControlEstoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjetoIntegrador`.`ControlEstoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ProjetoIntegrador`.`ControlEstoque` (
  `IDaparelho` INT NOT NULL,
  `TipoAparelho` VARCHAR(45) NULL,
  `EntradaData` DATE NULL,
  `SaidaData` DATE NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`IDaparelho`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ProjetoIntegrador`.`Cadastros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjetoIntegrador`.`Cadastros` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ProjetoIntegrador`.`Cadastros` (
  `LoginSIAPGE` INT NOT NULL,
  `NomeGE` VARCHAR(45) NOT NULL,
  `emailGE` VARCHAR(45) NOT NULL,
  `senhaGE` VARCHAR(45) NOT NULL,
  `ConfirmaSenhaGE` VARCHAR(45) NOT NULL,
  `ControlEstoque_IDaparelho` INT NOT NULL,
  PRIMARY KEY (`LoginSIAPGE`, `ControlEstoque_IDaparelho`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `SIAP_UNIQUE` ON `ProjetoIntegrador`.`Cadastros` (`LoginSIAPGE` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `NomeGE_UNIQUE` ON `ProjetoIntegrador`.`Cadastros` (`NomeGE` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `emailGE_UNIQUE` ON `ProjetoIntegrador`.`Cadastros` (`emailGE` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `senhaGE_UNIQUE` ON `ProjetoIntegrador`.`Cadastros` (`senhaGE` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `ConfirmaSenhaGE_UNIQUE` ON `ProjetoIntegrador`.`Cadastros` (`ConfirmaSenhaGE` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ProjetoIntegrador`.`LoginADM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjetoIntegrador`.`LoginADM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ProjetoIntegrador`.`LoginADM` (
  `login` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `Cadastros_LoginSIAPGE` INT NOT NULL,
  PRIMARY KEY (`login`, `Cadastros_LoginSIAPGE`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ProjetoIntegrador`.`CadastroReserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjetoIntegrador`.`CadastroReserva` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ProjetoIntegrador`.`CadastroReserva` (
  `SIAP` INT NOT NULL,
  `TipoAparelho` VARCHAR(45) NULL,
  `ID` INT NULL,
  `Data` DATE NULL,
  `horarioInicio` VARCHAR(45) NULL,
  `horarioFim` VARCHAR(45) NULL,
  PRIMARY KEY (`SIAP`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ProjetoIntegrador`.`Cadastros_has_CadastroReserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjetoIntegrador`.`Cadastros_has_CadastroReserva` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ProjetoIntegrador`.`Cadastros_has_CadastroReserva` (
  `Cadastros_LoginSIAPGE` INT NOT NULL,
  `CadastroReserva_SIAP` INT NOT NULL,
  PRIMARY KEY (`Cadastros_LoginSIAPGE`, `CadastroReserva_SIAP`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
